### ISSUE TITLE
CustomTarget error

### ISSUE THREAD

**Issue by emailsubjekt** [TakuSemba/Spotlight#74]
I get this when setting custom target in a java project ( No kotlin, cause that's how I roll) 

        Spotlight.with(this)
                .setOverlayColor(R.color.background)
                .setDuration(1000L)
                .setAnimation(new DecelerateInterpolator(2f))
//                .setTargets(fab, secondTarget, thirdTarget ...)
//                .setTargets(simpleTarget, simpleTarget2)                //customTarget
                .setTargets(customTarget, customTarget2)                //customTarget
        .setClosedOnTouchedOutside(true)
                .setOnSpotlightStateListener(new OnSpotlightStateChangedListener() {
                    @Override
                    public void onStarted() {
                        Toast.makeText(MainActivity.this, "spotlight is started", Toast.LENGTH_SHORT).show();
                    }

                    @Override
                    public void onEnded() {
                        Toast.makeText(MainActivity.this, "spotlight is ended", Toast.LENGTH_SHORT).show();
                        
                    }
                })
                .start();

ERROR
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.spotlighttest, PID: 22247
    java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5122)
        at android.view.ViewGroup.addView(ViewGroup.java:4953)
        at android.view.ViewGroup.addView(ViewGroup.java:4893)
        at android.view.ViewGroup.addView(ViewGroup.java:4866)
        at com.takusemba.spotlight.Spotlight.startTarget(Spotlight.java:183)
        at com.takusemba.spotlight.Spotlight.access$300(Spotlight.java:22)
        at com.takusemba.spotlight.Spotlight$3.onAnimationEnd(Spotlight.java:203)
        at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1209)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1449)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.-wrap2(Unknown Source:0)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
I/zygote64: WaitForGcToComplete blocked for 55.122ms for cause HeapTrim
Application terminated.

**Comment by TakuSemba** [comment]
This is the same as https://github.com/TakuSemba/Spotlight/issues/56
